/**
 * ============================================================
 * RUSH HOUR VILLAINS — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on April 28, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Rush Hour Villains",
  "tagline": "Ultimate Drivers Survival Guide",
  "preloaderTagline": "Ultimate Drivers Survival Guide",
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "About Us",
      "subtitle": ""
    },
    "contact": {
      "label": "Reporting is Key"
    }
  },
  "attorneyName": "",
  "attorneyDegree": "",
  "attorneyCredentials": [],
  "aboutBio1": "",
  "aboutBio2": "",
  "attorneyPhoto": "",
  "aboutNavLabel": "About Us",
  "attorneys": [
    {
      "name": "",
      "degree": "",
      "photo": "",
      "credentials": [],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "",
  "phoneRaw": "",
  "fax": "",
  "email": "",
  "address": "",
  "city": "",
  "state": "",
  "stateAbbr": "",
  "zip": "",
  "hours": [],
  "socialLinks": [],
  "stats": [
    {
      "num": "71",
      "label": "Villains Identified",
      "animate": true
    }
  ],
  "colors": {
    "navy": "#1c1c1c",
    "navyLight": "#424242",
    "gold": "#e8e11e",
    "goldLight": "#ff0000",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#faf6ec",
    "chrome": "#1c1c1c"
  },
  "fontColors": {
    "heading": "#1c1c1c",
    "body": "#5c5a53",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Lora",
  "fontBody": "Source Sans 3",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#424242",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#424242",
    "overlayOpacity": 0.5,
    "videoClips": [
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-06.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1.5,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-08.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "bottom center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Surviving Your Drive, One Villain at a Time",
  "heroSubline": "Welcome to the definitive field manual for surviving the architects of daily gridlock. We unmask the rogues of the road to help you identify the monsters turning your commute into a high-stakes saga. Strap in and master the tactics needed to navigate the asphalt’s most wanted.",
  "heroTrustBullets": [
    "8+ Identified Clans",
    "70+ Known Villains",
    "10+ Afflictions",
    "One Hero"
  ],
  "heroPrimaryLabel": "Report Sighting",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Villain identification",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "identification",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "Sighting Hotline",
  "contactSubline": "Reporting a Villain sighting is critical to road travel stability.",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Report Sighting",
  "pageToggles": {
    "about": false,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "identification",
      "navLabel": "Identification",
      "emoji": "🫆",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "fees",
          "label": "Villain Genealogy",
          "background": "alt",
          "anchorId": "identification",
          "heading": "Clan Identification",
          "subtitle": "The first step in identifying a villain is to determine which clan your suspect belongs to. There are 8 known clans operating today and we've put together this intuitive chart to help with the clan identification process.",
          "col1Label": "Traits / Description",
          "col2Label": "Villain Clan",
          "col3Label": "Special Precautions",
          "disclaimer": "Villains can mutate and sometime share common traits. The RHV is not responsible for a false identification by a commuter.",
          "items": [
            {
              "service": "Older model, parts falling off, re-engineered components, rust",
              "amount": "Junkyard Dawgs",
              "detail": "Leave plenty of space to dodge car parts, and oil slicks or splatter from other various  fluids.",
              "note": "",
              "linkLabel": "Clan Page",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": ""
            },
            {
              "service": "Loud terrible music, flashing lights, lots of bling,",
              "amount": "Showtime",
              "detail": "Roll up your windows, put on some sun shades, maybe turn up your tunes a little.",
              "note": "",
              "linkLabel": "Clan Page",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "service": "Excessive acceleration, in a hurry, negotiating traffic terribly, not courteous",
              "amount": "Grand Pricks",
              "detail": "Don't make any sudden decelerations/stops, leave space for diving, check the shoulder before making any turns",
              "note": "",
              "linkLabel": "Clan Page",
              "linkType": "internal",
              "linkUrl": "grand-pricks",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "timeline",
          "label": "Villain Genealogy",
          "background": "dark",
          "anchorId": "clan-identification",
          "heading": "Clan Identification",
          "subtitle": "The first step in identifying a villain is to determine which clan your suspect belongs to. There are 8 known clans operating today and we've put together this intuitive chart to help with the clan identification process.",
          "items": [
            {
              "date": "",
              "title": "Older model, parts falling off, re-engineered components, rust",
              "body": "Leave plenty of space to dodge car parts, and oil slicks or splatter from other various  fluids.",
              "linkLabel": "Junkyard Dawgs Clan",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Loud terrible music, flashing lights, lots of bling,",
              "body": "Roll up your windows, put on some sun shades, maybe turn up your tunes a little.",
              "linkLabel": "Showtime Clan",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Excessive acceleration, in a hurry, negotiating traffic terribly, not courteous",
              "body": "Don't make any sudden decelerations/stops, leave space for diving, check the shoulder before making any turns",
              "linkLabel": "Grand Pricks Clan",
              "linkType": "internal",
              "linkUrl": "grand-pricks",
              "anchorId": ""
            }
          ]
        }
      ]
    },
    {
      "slug": "afflictions",
      "navLabel": "Afflictions",
      "emoji": "🤒",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "flip-cards",
          "label": "Contagious",
          "background": "light",
          "anchorId": "afflictions",
          "heading": "Afflictions",
          "subtitle": "Villains are no different than anyone else, they too are susceptible to silly trends and bad decisions. These ridiculous afflictions can turn any dangerous villains, into a notoriously dangerous villain in the blink of a tiktok video.",
          "maxCols": 2,
          "items": [
            {
              "name": "Co-Pet",
              "tagline": "We all love our furry friends, but not theirs. The lap companion decreases reaction time and reduces vision.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/co-pet.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Doplertitious",
              "tagline": "During stormy weather some villains experience a sick lonely feeling prompting them to turn on every flashing light they have to alert others of their location, which in turn blinds and frustrates every living creature around them.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/doplertitious.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Ear Buddy",
              "tagline": "More often found with convertible villains, this affliction is caused by feelings of inferiority. Having the top off isn't enough to feel important, so having your phone constantly connect to your ear like you're needed at all times give them their high. Is it charged or working, probably not. But they are too busy looking like a fool to worry about that.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/ear-buddy.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Emergency Road Block",
              "tagline": "With symptoms of hearing loss, and spatial awareness, ERB can make some villains look like they are in a dream like state, while causing a nightmare of a roadblock for emergency vehicles.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/emergency-road-block.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Holey Moley",
              "tagline": "Nobody loves a good pothole like a villain suffering from decreased pain sensation. Villains suffering from HM often seem to steer their rigs directly at these ruts like they hate their suspensions.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/holey-moley.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Lane Envy",
              "tagline": "The grass is always green in the other lane when a villain contracts this affliction, that causes tunnel vision and reduced depth perception.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/lane-envy.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Wheeler Dealer",
              "tagline": "Vehicle tats, license plate covers, and front license plates displaying their dealerships logos, are often symptoms of a villain suffering from this terribly commercial marketing illness that was actually contracted from the dealership being showcased.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/wheeler-dealer.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            }
          ]
        }
      ]
    },
    {
      "slug": "villains",
      "navLabel": "Villains",
      "emoji": "🧟‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "steps",
          "label": "Family Bloodlines",
          "background": "dark",
          "anchorId": "villain-clans",
          "heading": "Villain Clans",
          "subtitle": "",
          "items": [
            {
              "title": "Junkyard Dawgs",
              "body": "The mystery machine junkers known as the Junkyard Dawgs",
              "linkLabel": "Junkyard Dawgs",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": "",
              "imagePath": "clans/junkyarddawgs.png",
              "imageSize": "sm"
            },
            {
              "title": "Bubble Brigade",
              "body": "In a world by themselves.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/bubblebrigade.png",
              "imageSize": "sm"
            },
            {
              "title": "Decepticars",
              "body": "Cars aren't who they look like.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/decepticars.png",
              "imageSize": "sm"
            },
            {
              "title": "Grand Pricks",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/grandpricks.png",
              "imageSize": "sm"
            },
            {
              "title": "Kinevils",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/kinevils.png",
              "imageSize": "sm"
            },
            {
              "title": "OMGs",
              "body": "We can't even believe it.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/omgs.png",
              "imageSize": "sm"
            },
            {
              "title": "Showtime",
              "body": "Lights, camera, action!",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/showtime.png",
              "imageSize": "sm"
            },
            {
              "title": "Slow Moes",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/slowmoes.png",
              "imageSize": "sm"
            }
          ]
        }
      ]
    },
    {
      "slug": "junkyard-dawgs",
      "navLabel": "Junkyard Dawgs",
      "emoji": "🦴",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Rough Rough",
          "background": "dark",
          "anchorId": "junkyard-dawgs",
          "heading": "Junkyard Dawgs",
          "body": "This crusty crew won't win any beauty contests, or drag races, but they'll still be roaming the neighborhood well past their prime.",
          "imagePath": "clans/junkyarddawgs.png",
          "imagePosition": "left",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "junkyard-villains",
          "heading": "The Yard",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Red Dragon",
              "tagline": "Street legal or not, this country villain with flowing locks lives in the past, and usually roams the countryside. Oh, and that choking smoke ain't coming from the tires.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/red-dragon.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "This beast can turn an over the hill driver, back into a 16 year with a learners permit who's taken pops dream machine out for a spin without his permission.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Pavement",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dry Counties",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Engine Smoke",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Tuned out Air Horn",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cigarette butts",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Larry Towncar",
              "tagline": "This OG's car doesn't need repair shop, it needs a junkyard",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/larry-towncar.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Slowing traffic down with extreme precision using nothing but friction and loose car parts.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Passing Lanes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dashed Centerline",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Busted Fuel Line",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Parts",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Oil slick",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "ReTuned",
              "tagline": "You won't find this disastrous glitch in the matrix at any dealership and its debatable whether it will make it to its destination, much less down the street..",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/retuned.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Cranking up. Not much of an ability, but this Frankensteined vehicle is proof that backyard engineering is alive, but not well.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Bad re-engineering",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Spare Change",
              "tagline": "Spare Change is a relentless, chaotic driver piloting a rusted-out rig that has been running on a single, undersized \"donut\" spare tire for months longer than engineering allows.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/spare-change.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Driven by a permanent sense of urgent tardiness, he treats the highway like a high-stakes obstacle course, ignoring every safety warning ever printed on a sidewall.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Potholes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Spark Showers",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Lug Nut Shrapnel",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "grand-pricks",
      "navLabel": "Grand Pricks",
      "emoji": "💨",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Our Rules, Your Problem",
          "background": "dark",
          "anchorId": "grand-pricks",
          "heading": "Grand Pricks",
          "body": "",
          "imagePath": "clans/grandpricks.png",
          "imagePosition": "left",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "the-strip",
          "heading": "The Strip",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Red Dragon",
              "tagline": "Street legal or not, this country villain with flowing locks lives in the past, and usually roams the countryside. Oh, and that choking smoke ain't coming from the tires.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/red-dragon.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "This beast can turn an over the hill driver, back into a 16 year with a learners permit who's taken pops dream machine out for a spin without his permission.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Pavement",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dry Counties",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Engine Smoke",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Tuned out Air Horn",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cigarette butts",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Larry Towncar",
              "tagline": "This OG's car doesn't need repair shop, it needs a junkyard",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/larry-towncar.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Slowing traffic down with extreme precision using nothing but friction and loose car parts.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Passing Lanes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dashed Centerline",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Busted Fuel Line",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Parts",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Oil slick",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "ReTuned",
              "tagline": "You won't find this disastrous glitch in the matrix at any dealership and its debatable whether it will make it to its destination, much less down the street..",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/retuned.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Cranking up. Not much of an ability, but this Frankensteined vehicle is proof that backyard engineering is alive, but not well.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Bad re-engineering",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Spare Change",
              "tagline": "Spare Change is a relentless, chaotic driver piloting a rusted-out rig that has been running on a single, undersized \"donut\" spare tire for months longer than engineering allows.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/spare-change.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Driven by a permanent sense of urgent tardiness, he treats the highway like a high-stakes obstacle course, ignoring every safety warning ever printed on a sidewall.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Potholes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Spark Showers",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Lug Nut Shrapnel",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "heroes",
      "navLabel": "Heroes",
      "emoji": "🦸‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "glossary",
      "navLabel": "Glossary",
      "emoji": "📖",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    }
  ],
  "aboutSections": [],
  "homeSections": [],
  "footerBio": "Surviving Your Drive, One Villain at a Time",
  "animateStats": true,
  "contactSubmitLabel": "Update Villain Database",
  "contactSuccessMsg": "Thank you for the Update...drive safe!",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public",
    "cp-3": "public",
    "cp-4": "public",
    "cp-5": "public",
    "cp-6": "public"
  },
  "_savedAt": 1777411188597
};
