/**
 * ============================================================
 * RUSH HOUR VILLAINS — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on April 27, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Rush Hour Villains",
  "tagline": "Official Survival Guide",
  "preloaderTagline": "Official Survival Guide",
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "About Us",
      "subtitle": ""
    },
    "contact": {
      "label": "Reporting is Key"
    }
  },
  "attorneyName": "",
  "attorneyDegree": "",
  "attorneyCredentials": [],
  "aboutBio1": "",
  "aboutBio2": "",
  "attorneyPhoto": "",
  "aboutNavLabel": "About Us",
  "attorneys": [
    {
      "name": "",
      "degree": "",
      "photo": "",
      "credentials": [],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "",
  "phoneRaw": "",
  "fax": "",
  "email": "",
  "address": "",
  "city": "",
  "state": "",
  "stateAbbr": "",
  "zip": "",
  "hours": [],
  "socialLinks": [],
  "stats": [],
  "colors": {
    "navy": "#1c1c1c",
    "navyLight": "#424242",
    "gold": "#e8e11e",
    "goldLight": "#ff0000",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#faf6ec",
    "chrome": "#1c1c1c"
  },
  "fontColors": {
    "heading": "#1c1c1c",
    "body": "#5c5a53",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Lora",
  "fontBody": "Source Sans 3",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#424242",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#424242",
    "overlayOpacity": 0.5,
    "videoClips": [
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-08.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "bottom center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-06.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Knowing Your Enemies, Is Half the Battle",
  "heroSubline": "Welcome to the definitive field manual for surviving the architects of daily gridlock. We unmask the rogues of the road to help you identify the monsters turning your commute into a high-stakes saga. Strap in and master the tactics needed to navigate the asphalt’s most wanted.",
  "heroTrustBullets": [
    "8+ Identified Clans",
    "70+ Known Villains",
    "10+ Afflictions"
  ],
  "heroPrimaryLabel": "Report Sighting",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Villain identification",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "home",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "Sighting Hotline",
  "contactSubline": "Reporting a Villain sighting is critical to road travel stability.",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Report Sighting",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "identification",
      "navLabel": "Identification",
      "emoji": "🫆",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "afflictions",
      "navLabel": "Afflictions",
      "emoji": "🤒",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "villains",
      "navLabel": "Villains",
      "emoji": "🧟‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "steps",
          "label": "Family Bloodlines",
          "background": "dark",
          "anchorId": "villain-clans",
          "heading": "Villain Clans",
          "subtitle": "",
          "items": [
            {
              "title": "Junkyard Dawgs",
              "body": "The mystery machine junkers known as the Junkyard Dawgs",
              "linkLabel": "Junkyard Dawgs",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": "",
              "imagePath": "clans/junkyarddawgs.png",
              "imageSize": "full"
            },
            {
              "title": "Bubble Brigade",
              "body": "In a world by themselves.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/bubblebrigade.png",
              "imageSize": "full"
            },
            {
              "title": "Decepticars",
              "body": "Cars aren't who they look like.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/decepticars.png",
              "imageSize": "full"
            },
            {
              "title": "Grand Pricks",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/grandpricks.png",
              "imageSize": "full"
            },
            {
              "title": "Kinevils",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/kinevils.png",
              "imageSize": "full"
            },
            {
              "title": "OMGs",
              "body": "We can't even believe it.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/omgs.png",
              "imageSize": "full"
            },
            {
              "title": "Showtime",
              "body": "Lights, camera, action!",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/showtime.png",
              "imageSize": "full"
            },
            {
              "title": "Slow Moes",
              "body": "",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": "",
              "imagePath": "clans/slowmoes.png",
              "imageSize": "full"
            }
          ]
        }
      ]
    },
    {
      "slug": "junkyard-dawgs",
      "navLabel": "Junkyard Dawgs",
      "emoji": "🦴",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Villain Clan",
          "background": "dark",
          "anchorId": "junkyard-dawgs",
          "heading": "Junkyard Dawgs",
          "body": "This crusty crew won't win any beauty contests, or drag races, but they'll still be roaming the neighborhood well past their prime.",
          "imagePath": "clans/junkyarddawgs.png",
          "imagePosition": "right",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "The Villains",
          "background": "dark",
          "anchorId": "the-villains",
          "heading": "",
          "subtitle": "",
          "items": [
            {
              "name": "Red Dragon",
              "tagline": "Rarely found in the city, this country villain with flowing locks lives in the past.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/reddragon.png",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "Street legal or not, the choking smoke ain't coming from the tires.",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Pavement",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dry Counties",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Engine Smoke",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Tuned out Air Horn",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cigarette butsd",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Larry Towncar",
              "tagline": "This OG's car doesn't need repair shop, it needs a junkyard",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/larrytowncar.png",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "Slowing traffic down with extreme precision using nothing but friction and loose car parts.",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Passing Lanes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dashed Centerline",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Busted Fuel Line",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Parts",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Oil slick",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "ReTuned",
              "tagline": "You won't find this hybrid villain at any dealership and its debatable whether it's even street legal.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/retuned.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "Frankensteining a stock vehicle !",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Bad re-engineering",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "grand-pricks",
      "navLabel": "Grand Pricks",
      "emoji": "💨",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "heroes",
      "navLabel": "Heroes",
      "emoji": "🦸‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "glossary",
      "navLabel": "Glossary",
      "emoji": "📖",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    }
  ],
  "aboutSections": [],
  "homeSections": [],
  "footerBio": "Knowing Your Enemies, is Half the Battle",
  "animateStats": false,
  "contactSubmitLabel": "",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public",
    "cp-3": "public",
    "cp-4": "public"
  },
  "_savedAt": 1777262734401
};
