/**
 * ============================================================
 * RUSH HOUR VILLAINS — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on April 30, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Rush Hour Villains",
  "tagline": "Ultimate Drivers Survival Guide",
  "preloaderTagline": "Ultimate Drivers Survival Guide",
  "logoPrimary": "logos/rhv-pipes-white.png",
  "logoAlternate": "logos/rhv-pipes-color.png",
  "logoHeaderChoice": "primary",
  "logoHeaderHeight": 60,
  "logoSplashChoice": "alternate",
  "logoSplashHeight": 150,
  "logoSplashMode": "logo-tagline",
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "About Us",
      "subtitle": ""
    },
    "contact": {
      "label": "Reporting is Key"
    }
  },
  "attorneyName": "",
  "attorneyDegree": "",
  "attorneyCredentials": [],
  "aboutBio1": "",
  "aboutBio2": "",
  "attorneyPhoto": "",
  "aboutNavLabel": "About Us",
  "attorneys": [
    {
      "name": "",
      "degree": "",
      "photo": "",
      "credentials": [],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "",
  "phoneRaw": "",
  "fax": "",
  "email": "",
  "address": "",
  "city": "",
  "state": "",
  "stateAbbr": "",
  "zip": "",
  "hours": [],
  "socialLinks": [],
  "stats": [
    {
      "num": "71",
      "label": "Villains Identified",
      "animate": true
    }
  ],
  "colors": {
    "navy": "#1c1c1c",
    "navyLight": "#424242",
    "gold": "#e8e11e",
    "goldLight": "#ff0000",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#faf6ec",
    "chrome": "#1c1c1c"
  },
  "fontColors": {
    "heading": "#1c1c1c",
    "body": "#5c5a53",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Lora",
  "fontBody": "Source Sans 3",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#424242",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#424242",
    "overlayOpacity": 0.5,
    "videoClips": [
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-03.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1.5,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-02.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 5
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Surviving Your Drive, One Villain at a Time",
  "heroSubline": "Welcome to the definitive field manual for surviving the architects of daily gridlock. We unmask the rogues of the road to help you identify the monsters turning your commute into a high-stakes saga. Strap in and master the tactics needed to navigate the asphalt’s most wanted.",
  "heroTrustBullets": [
    "8+ Identified Clans",
    "70+ Known Villains",
    "10+ Afflictions",
    "One Hero"
  ],
  "heroPrimaryLabel": "Report Sighting",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Villain identification",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "identification",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "Sighting Hotline",
  "contactSubline": "Reporting a Villain sighting is critical to road travel stability.",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Report Sighting",
  "pageToggles": {
    "about": false,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "identification",
      "navLabel": "Identification",
      "emoji": "🫆",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "timeline",
          "label": "Villain Genealogy",
          "background": "dark",
          "anchorId": "clan-identification",
          "heading": "Clan Identification",
          "subtitle": "The first step in identifying a villain is to determine which clan your suspect belongs to. There are 8 known clans operating today and we've put together this intuitive chart to help with the clan identification process.",
          "items": [
            {
              "date": "",
              "title": "Oblivious of others, Loves social media, One perspective",
              "body": "",
              "linkLabel": "Bubble Brigade Clan",
              "linkType": "internal",
              "linkUrl": "bubble-brigade",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Deceiving appearance, Sudden driving changes",
              "body": "",
              "linkLabel": "Decepitcars Clan",
              "linkType": "internal",
              "linkUrl": "decepticars",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Older model, Parts falling off, Re-engineered components, Rust",
              "body": "Leave plenty of space to dodge car parts, and oil slicks or splatter from other various fluids.",
              "linkLabel": "Junkyard Dawgs Clan",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Excessive acceleration, In a hurry, Negotiating traffic terribly, Not courteous",
              "body": "Don't make any sudden decelerations/stops, leave space for diving, check the shoulder before making any turns",
              "linkLabel": "Grand Pricks Clan",
              "linkType": "internal",
              "linkUrl": "grand-pricks",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Aggressive, Redefines roadway use, Unfazed by Weather",
              "body": "",
              "linkLabel": "KinEvils Clan",
              "linkType": "internal",
              "linkUrl": "kinevils",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Focuses on anything but driving, No perception of driving concepts, Female",
              "body": "",
              "linkLabel": "OMGs Clan",
              "linkType": "internal",
              "linkUrl": "omgs",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Loud terrible music, Flashing lights, Lots of bling,",
              "body": "Roll up your windows, put on some sun shades, maybe turn up your tunes a little.",
              "linkLabel": "Showtime Clan",
              "linkType": "internal",
              "linkUrl": "showtime",
              "anchorId": ""
            },
            {
              "date": "",
              "title": "Moves slowly, Loves brakes, seems lost, Lane changing issues, Fear",
              "body": "Early detection is paramount, so that you don't get stuck behind them.",
              "linkLabel": "Slow Moes Clan",
              "linkType": "internal",
              "linkUrl": "slow-moes",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "link",
          "label": "",
          "background": "light",
          "anchorId": "link",
          "linkType": "internal",
          "linkLabel": "Identify An Affliction",
          "linkUrl": "afflictions",
          "link_anchorId": ""
        }
      ]
    },
    {
      "slug": "afflictions",
      "navLabel": "Afflictions",
      "emoji": "🤒",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "flip-cards",
          "label": "Contagious",
          "background": "light",
          "anchorId": "afflictions",
          "heading": "Afflictions",
          "subtitle": "Villains are no different than anyone else, they too are susceptible to silly trends and bad decisions. These ridiculous afflictions can turn any dangerous villains, into a notoriously dangerous villain in the blink of a tiktok video.",
          "maxCols": 2,
          "items": [
            {
              "name": "Co-Pet",
              "tagline": "We all love our furry friends, but not theirs. The lap companion decreases reaction time and reduces vision.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/co-pet.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Doplertitious",
              "tagline": "During stormy weather some villains experience a sick lonely feeling prompting them to turn on every flashing light they have to alert others of their location, which in turn blinds and frustrates every living creature around them.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/doplertitious.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Ear Buddy",
              "tagline": "More often found with convertible villains, this affliction is caused by feelings of inferiority. Having the top off isn't enough to feel important, so having your phone constantly connect to your ear like you're needed at all times give them their high. Is it charged or working, probably not. But they are too busy looking like a fool to worry about that.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/ear-buddy.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Emergency Road Block",
              "tagline": "With symptoms of hearing loss, and spatial awareness, ERB can make some villains look like they are in a dream like state, while causing a nightmare of a roadblock for emergency vehicles.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/emergency-road-block.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Holey Moley",
              "tagline": "Nobody loves a good pothole like a villain suffering from decreased pain sensation. Villains suffering from HM often seem to steer their rigs directly at these ruts like they hate their suspensions.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/holey-moley.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Lane Envy",
              "tagline": "The grass is always green in the other lane when a villain contracts this affliction, that causes tunnel vision and reduced depth perception.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/lane-envy.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Wheeler Dealer",
              "tagline": "Vehicle tats, license plate covers, and front license plates displaying their dealerships logos, are often symptoms of a villain suffering from this terribly commercial marketing illness that was actually contracted from the dealership being showcased.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "afflictions/wheeler-dealer.jpg",
              "imageSize": "sq",
              "ribbon": "Afflictions",
              "note": "",
              "details": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Report an Affliction",
          "secondary_linkUrl": "rhv-forms",
          "secondary_anchorId": "report-an-affliction"
        }
      ]
    },
    {
      "slug": "villains",
      "navLabel": "Villains",
      "emoji": "🧟‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "steps",
          "label": "Family Bloodlines",
          "background": "dark",
          "anchorId": "villain-clans",
          "heading": "Villain Clans",
          "subtitle": "",
          "items": [
            {
              "title": "Junkyard Dawgs",
              "body": "The mystery machine junkers known as the Junkyard Dawgs",
              "linkLabel": "Junkyard Dawgs",
              "linkType": "internal",
              "linkUrl": "junkyard-dawgs",
              "anchorId": "",
              "imagePath": "clans/junkyarddawgs.png",
              "imageSize": "sm"
            },
            {
              "title": "Bubble Brigade",
              "body": "In a world by themselves.",
              "linkLabel": "Bubble Brigade",
              "linkType": "internal",
              "linkUrl": "bubble-brigade",
              "anchorId": "",
              "imagePath": "clans/bubblebrigade.png",
              "imageSize": "sm"
            },
            {
              "title": "Decepticars",
              "body": "Cars aren't who they look like.",
              "linkLabel": "Decepticars",
              "linkType": "internal",
              "linkUrl": "decepticars",
              "anchorId": "",
              "imagePath": "clans/decepticars.png",
              "imageSize": "sm"
            },
            {
              "title": "Grand Pricks",
              "body": "",
              "linkLabel": "Grand Pricks",
              "linkType": "internal",
              "linkUrl": "grand-pricks",
              "anchorId": "",
              "imagePath": "clans/grandpricks.png",
              "imageSize": "sm"
            },
            {
              "title": "Kinevils",
              "body": "",
              "linkLabel": "KinEvils",
              "linkType": "internal",
              "linkUrl": "kinevils",
              "anchorId": "",
              "imagePath": "clans/kinevils.png",
              "imageSize": "sm"
            },
            {
              "title": "OMGs",
              "body": "We can't even believe it.",
              "linkLabel": "OMGs",
              "linkType": "internal",
              "linkUrl": "omgs",
              "anchorId": "",
              "imagePath": "clans/omgs.png",
              "imageSize": "sm"
            },
            {
              "title": "Showtime",
              "body": "Lights, camera, action!",
              "linkLabel": "Showtime",
              "linkType": "internal",
              "linkUrl": "showtime",
              "anchorId": "",
              "imagePath": "clans/showtime.png",
              "imageSize": "sm"
            },
            {
              "title": "Slow Moes",
              "body": "",
              "linkLabel": "Slow Moes",
              "linkType": "internal",
              "linkUrl": "slow-moes",
              "anchorId": "",
              "imagePath": "clans/slowmoes.png",
              "imageSize": "sm"
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Report an Undocumented Villain",
          "secondary_linkUrl": "rhv-forms",
          "secondary_anchorId": "new-villain-encounter"
        }
      ]
    },
    {
      "slug": "bubble-brigade",
      "navLabel": "Bubble Brigade",
      "emoji": "🫧",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Oblivious and On My Way",
          "background": "dark",
          "anchorId": "bubble-brigade",
          "heading": "Bubble Brigade",
          "body": "",
          "imagePath": "clans/bubblebrigade.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "bubble-villains",
          "heading": "Bubble Villains",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Quicksilverette",
              "tagline": "This villain is hot, but a capable, responsible driver she is not. If her driving were half as good as she is at getting free drinks all night, she'd be a Nascar driving instructor.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/quicksilverette.jpg",
              "imageSize": "sq",
              "ribbon": "OMGs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Can misinterpret all rules of the road, while pretending she knows what she is doing.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Automobiles",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Stop signs",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Traffic signals",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Parking lots",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "One-way streets",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Streets",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Merging",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Etc.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Lipstick Mirror",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Visor Mirrors",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "SU-Vera",
              "tagline": "Wants to be just like her villain man, driving a truck made from indestructible steel.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/su-vera.jpg",
              "imageSize": "sq",
              "ribbon": "OMGs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Lacks fear of breaking laws of the road or your bones.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Losing truck in divorce",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "He Drives",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "2 tons of Steel",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Being Short",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "decepticars",
      "navLabel": "Decepticars",
      "emoji": "🚘",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "What Are You Looking At",
          "background": "dark",
          "anchorId": "decepticars",
          "heading": "Decepticars",
          "body": "",
          "imagePath": "clans/decepticars.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "decepticars-villains",
          "heading": "The Deceptors",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Handiscammer",
              "tagline": "This undisabled villain parades around displaying the wheeled emblem, stealing parking spots reserved for villains in true need.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/handiscammer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being a fully functioning jackass.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "No available handicap spots",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Vocal Heros",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Portable Disabled Mirror Badge",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Lion Tamer",
              "tagline": "Am I seeing things in slow motion, or is that monster car really going that slow? This villain has appearance of being a high performance, but the only thing high here is the maintenance. .",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/lion-tamer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Clogging up traffic with the fear of their own abilities",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Running Late",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "He Drives",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being Short",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "junkyard-dawgs",
      "navLabel": "Junkyard Dawgs",
      "emoji": "🦴",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Rough Rough",
          "background": "dark",
          "anchorId": "junkyard-dawgs",
          "heading": "Junkyard Dawgs",
          "body": "This crusty crew won't win any beauty contests, or drag races, but they'll still be roaming the neighborhood well past their prime.",
          "imagePath": "clans/junkyarddawgs.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "junkyard-villains",
          "heading": "The Yard",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Larry Towncar",
              "tagline": "This OG's car doesn't need repair shop, it needs a junkyard",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/larry-towncar.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Slowing traffic down with extreme precision using nothing but friction and loose car parts.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Passing Lanes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dashed Centerline",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Busted Fuel Line",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Parts",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Oil slick",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Red Dragon",
              "tagline": "Street legal or not, this country villain with flowing locks lives in the past, and usually roams the countryside. Oh, and that choking smoke ain't coming from the tires.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/red-dragon.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "This beast can turn an over the hill driver, back into a 16 year with a learners permit who's taken pops dream machine out for a spin without his permission.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Pavement",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dry Counties",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Engine Smoke",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Tuned out Air Horn",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cigarette butts",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "ReTuned",
              "tagline": "You won't find this disastrous glitch in the matrix at any dealership and its debatable whether it will make it to its destination, much less down the street..",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/retuned.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Cranking up. Not much of an ability, but this Frankensteined vehicle is proof that backyard engineering is alive, but not well.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Bad re-engineering",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Spare Change",
              "tagline": "Spare Change is a relentless, chaotic driver piloting a rusted-out rig that has been running on a single, undersized \"donut\" spare tire for months longer than engineering allows.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/spare-change.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Driven by a permanent sense of urgent tardiness, he treats the highway like a high-stakes obstacle course, ignoring every safety warning ever printed on a sidewall.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Potholes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Spark Showers",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Lug Nut Shrapnel",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "grand-pricks",
      "navLabel": "Grand Pricks",
      "emoji": "💨",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Our Rules, Your Problem",
          "background": "dark",
          "anchorId": "grand-pricks",
          "heading": "Grand Pricks",
          "body": "",
          "imagePath": "clans/grandpricks.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "grand-villains",
          "heading": "The Strip",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Fly Bye",
              "tagline": "There are no lights or signs that are going to slow this illiterate villain.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/fly-bye.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Immunity to construction, school zone speed restrictions, and school bus stops.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Crossing Guards",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Speed Bumps",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Lead Foot",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Hazardous",
              "tagline": "With one press of a button, this villain believes they have been transformed into an Emergency vehicle, thus voiding all traffic laws.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/hazardous.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Prix",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "With one press of a button, this villain believes they have been transformed into an Emergency vehicle, thus voiding all traffic laws.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "No one caring",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Flashing bulbs of pain",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Head and Shoulders",
              "tagline": "Slow traffic can aggravate this villain to no end, so the DMV created shoulder lanes to cool his temper and fire up his engine.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/head-and-shoulders.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being a prick from great distances to an exit or merging sign.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Shoulder-less roads",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Alter Ego",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Special Centergy",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Nemesis",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Half-Nelson",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Later Gator",
              "tagline": "This villain doesn't care if its bumper to bumper traffic, ain't no one getting in.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/later-gator.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Accelerating and braking quickly, keeping the safe distance of 1 foot between vehicles.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Riding behind Ole Gapper",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Blame Changer",
              "tagline": "He’s as fast as they come, but struggles to read traffic patterns.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/blame-changer.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Changing lanes lightning quick without use of blinker or reason.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Inability to plan attack or see two cars ahead.",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Drag Queen",
              "tagline": "Green light means, Go, Go, Go...!",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/drag-queen.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Insane acceleration and great top speed between traffic lights...each time.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Timed traffic lights",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Wet Roads",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "El Cheetah",
              "tagline": "Is in a terrible rush and no one is making way for his speedy journey.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/el-cheetah.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Incredible straight-line speed.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Suffers from tunnel vision, has no depth perception, and doesn't understand passing lanes.",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "EXXitON",
              "tagline": "Traffic lights are for suckers when there's a perfectly located corner gas station.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/exxiton.jpg",
              "imageSize": "sq",
              "ribbon": "Grand Pricks",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Turning right thru the gas station and back onto the cross street seconds sooner without much wear and tear on the brake pads.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Washes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cement ballards",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapon",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Perfectly timed traffic lights",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "kinevils",
      "navLabel": "KinEvils",
      "emoji": "💀",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Our Road, Your Nightmare",
          "background": "dark",
          "anchorId": "kinevils",
          "heading": "KinEvils",
          "body": "",
          "imagePath": "clans/kinevils.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "kinevils-villains",
          "heading": "The Deceptors",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Handiscammer",
              "tagline": "This undisabled villain parades around displaying the wheeled emblem, stealing parking spots reserved for villains in true need.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/handiscammer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being a fully functioning jackass.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "No available handicap spots",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Vocal Heros",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Portable Disabled Mirror Badge",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Lion Tamer",
              "tagline": "Am I seeing things in slow motion, or is that monster car really going that slow? This villain has appearance of being a high performance, but the only thing high here is the maintenance. .",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/lion-tamer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Clogging up traffic with the fear of their own abilities",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Running Late",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "He Drives",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being Short",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "omgs",
      "navLabel": "OMGs",
      "emoji": "👩‍🎤",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Too Much Car, Too Little Clue",
          "background": "dark",
          "anchorId": "omgs",
          "heading": "OMGs",
          "body": "The myth that all women are bad drivers is just a myth, until you encounter this clan of females.",
          "imagePath": "clans/omgs.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "omgs-villains",
          "heading": "The Oh-Mys",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Quicksilverette",
              "tagline": "This villain is hot, but a capable, responsible driver she is not. If her driving were half as good as she is at getting free drinks all night, she'd be a Nascar driving instructor.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/quicksilverette.jpg",
              "imageSize": "sq",
              "ribbon": "OMGs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Can misinterpret all rules of the road, while pretending she knows what she is doing.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Automobiles",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Stop signs",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Traffic signals",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Parking lots",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "One-way streets",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Streets",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Merging",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Etc.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Lipstick Mirror",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Visor Mirrors",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "SU-Vera",
              "tagline": "Wants to be just like her villain man, driving a truck made from indestructible steel.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/su-vera.jpg",
              "imageSize": "sq",
              "ribbon": "OMGs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Lacks fear of breaking laws of the road or your bones.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Losing truck in divorce",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "He Drives",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "2 tons of Steel",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Being Short",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "showtime",
      "navLabel": "Showtime",
      "emoji": "🎬",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Making Traffic an Event",
          "background": "dark",
          "anchorId": "showtime",
          "heading": "Showtime",
          "body": "",
          "imagePath": "clans/showtime.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "showtime-villains",
          "heading": "The Deceptors",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Handiscammer",
              "tagline": "This undisabled villain parades around displaying the wheeled emblem, stealing parking spots reserved for villains in true need.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/handiscammer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being a fully functioning jackass.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "No available handicap spots",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Vocal Heros",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Portable Disabled Mirror Badge",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Lion Tamer",
              "tagline": "Am I seeing things in slow motion, or is that monster car really going that slow? This villain has appearance of being a high performance, but the only thing high here is the maintenance. .",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/lion-tamer.jpg",
              "imageSize": "sq",
              "ribbon": "Decepticars",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Clogging up traffic with the fear of their own abilities",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Running Late",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "He Drives",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Being Short",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "slow-moes",
      "navLabel": "Slow Moes",
      "emoji": "🦥",
      "enabled": true,
      "parent": "villains",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Plod On",
          "background": "dark",
          "anchorId": "slow-moes",
          "heading": "Slow Moes",
          "body": "When traffic is jammed, it's almost guaranteed that a Slow Moe is to blame. This group prides itself on pissing off grandmothers and Sunday drivers, both of whom seem eager to get nowhere compared to this lazy group.",
          "imagePath": "clans/slowmoes.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "slow-villains",
          "heading": "The Yard",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Red Dragon",
              "tagline": "Street legal or not, this country villain with flowing locks lives in the past, and usually roams the countryside. Oh, and that choking smoke ain't coming from the tires.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/red-dragon.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "This beast can turn an over the hill driver, back into a 16 year with a learners permit who's taken pops dream machine out for a spin without his permission.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Pavement",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dry Counties",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Engine Smoke",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Tuned out Air Horn",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Cigarette butts",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Larry Towncar",
              "tagline": "This OG's car doesn't need repair shop, it needs a junkyard",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/larry-towncar.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Slowing traffic down with extreme precision using nothing but friction and loose car parts.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Passing Lanes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Dashed Centerline",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Busted Fuel Line",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Car Parts",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Oil slick",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "ReTuned",
              "tagline": "You won't find this disastrous glitch in the matrix at any dealership and its debatable whether it will make it to its destination, much less down the street..",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/retuned.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Cranking up. Not much of an ability, but this Frankensteined vehicle is proof that backyard engineering is alive, but not well.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Bad re-engineering",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Spare Change",
              "tagline": "Spare Change is a relentless, chaotic driver piloting a rusted-out rig that has been running on a single, undersized \"donut\" spare tire for months longer than engineering allows.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "villains/spare-change.jpg",
              "imageSize": "sq",
              "ribbon": "Junkyard Dawgs",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Driven by a permanent sense of urgent tardiness, he treats the highway like a high-stakes obstacle course, ignoring every safety warning ever printed on a sidewall.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Potholes",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Highways",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapons",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Spark Showers",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Lug Nut Shrapnel",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "heroes",
      "navLabel": "Heroes",
      "emoji": "🦸‍♀️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Crime Fighting Villains",
          "background": "dark",
          "anchorId": "heros",
          "heading": "Heros",
          "body": "",
          "imagePath": "clans/heros.png",
          "imagePosition": "right",
          "imageMaxWidth": "300",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "flip-cards",
          "label": "",
          "background": "dark",
          "anchorId": "super-heros",
          "heading": "Super Heros",
          "subtitle": "",
          "maxCols": 2,
          "items": [
            {
              "name": "Half-Nelson",
              "tagline": "This villain is hot, but a capable, responsible driver she is not. If her driving were half as good as she is at getting free drinks all night, she'd be a Nascar driving instructor.",
              "price": "",
              "period": "",
              "icon": "",
              "imagePath": "heros/half-nelson.jpg",
              "imageSize": "sq",
              "ribbon": "Heros",
              "note": "",
              "details": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Abilities",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Occupying two lanes at one time, purposefully and dutifully.",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Weaknesses",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Wide Shoulders",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Special Weapon",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Rearview & Passenger Side Mirrors",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "Nemesis",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "Head and Shoulders",
                  "status": "",
                  "isGroup": false
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "slug": "glossary",
      "navLabel": "Glossary",
      "emoji": "📖",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": []
    },
    {
      "slug": "rhv-forms",
      "navLabel": "RHV Forms",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "form",
          "label": "New Epidemic",
          "background": "dark",
          "anchorId": "report-an-affliction",
          "heading": "Report an Affliction",
          "intro": "Report the finding and let us verify your discovery before it's too late.",
          "submitLabel": "File Report",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "text",
              "label": "Full Name",
              "placeholder": "Not required",
              "required": false,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "textarea",
              "label": "Description / Traits",
              "placeholder": "Describe the action or list the behavior/outcomes",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "text",
              "label": "Suggested Affliction Name",
              "placeholder": "Create a Descriptive Name",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "select",
              "label": "Location",
              "placeholder": "Where did you see the affliction",
              "required": true,
              "halfWidth": true,
              "options": [
                "Interstate",
                "Highway",
                "City Street",
                "County Road",
                "Side Street",
                "Parking Lot",
                "Other"
              ]
            },
            {
              "type": "select",
              "label": "Time of Day",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": [
                "Morning",
                "Noon",
                "Afternoon",
                "Night",
                "Other"
              ]
            }
          ]
        },
        {
          "type": "form",
          "label": "Undocumented",
          "background": "dark",
          "anchorId": "new-villain-encounter",
          "heading": "New Villain Encounter",
          "intro": "Report the finding and let us verify your discovery before it's too late.",
          "submitLabel": "File Report",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "text",
              "label": "Full Name",
              "placeholder": "Not required",
              "required": false,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "textarea",
              "label": "Description / Traits",
              "placeholder": "Describe the action or list the behavior/outcomes",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "text",
              "label": "Suggested Villain Name",
              "placeholder": "Create a Descriptive Name",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "select",
              "label": "Location",
              "placeholder": "Where did you see the villain",
              "required": true,
              "halfWidth": true,
              "options": [
                "Interstate",
                "Highway",
                "City Street",
                "County Road",
                "Side Street",
                "Parking Lot",
                "Other"
              ]
            },
            {
              "type": "select",
              "label": "Time of Day",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": [
                "Morning",
                "Noon",
                "Afternoon",
                "Night",
                "Other"
              ]
            }
          ]
        }
      ]
    }
  ],
  "aboutSections": [],
  "homeSections": [],
  "footerBio": "Surviving Your Drive, One Villain at a Time",
  "animateStats": true,
  "contactSubmitLabel": "Update Villain Database",
  "contactSuccessMsg": "Thank you for the Update...drive safe!",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public",
    "cp-3": "public",
    "cp-4": "public",
    "cp-5": "public",
    "cp-6": "public",
    "cp-7": "public",
    "cp-8": "public",
    "cp-9": "public",
    "cp-10": "public",
    "cp-11": "public",
    "cp-12": "public",
    "cp-13": "public"
  },
  "_savedAt": 1777526668241
};
